use std::{borrow::Cow, collections::HashMap};
use indexmap::{IndexMap, IndexSet};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use crate::{
    account::CiphertextCache,
    asset::AssetData,
    block::TopoHeight,
    crypto::{
        elgamal::CompressedCiphertext,
        Address,
        Hash,
        PrivateKey,
        Signature,
        HumanReadableProof,
    },
    serializer::Hexable,
    time::TimestampMillis,
    transaction::{
        builder::{FeeBuilder, TransactionTypeBuilder, UnsignedTransaction},
        extra_data::{PlaintextExtraData, UnknownExtraDataFormat},
        multisig::SignatureId,
        Reference,
        Role,
        TxVersion
    }
};
use super::{
    RPCTransaction,
    DataElement,
    DataValue,
    query::Query,
    default_false_value,
    default_true_value,
    daemon
};

/// Optional internal RPC method used by XSWD
/// To request in one time the permissions
/// example: balance, tracked assets etc is grouped into one
/// modal that propose to the user to set them in "always allow"
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct XSWDPrefetchPermissions {
    /// Description to be shown to the user
    pub reason: Option<String>,
    /// Request these permissions in advance
    pub permissions: IndexSet<String>,
}

/// Signer ID to use for signing the transaction
#[derive(Serialize, Deserialize, JsonSchema)]
pub struct SignerId {
    /// Signer index in the multisig setup.
    pub id: u8,
    /// Private key used by the signer.
    pub private_key: PrivateKey
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct BuildTransactionParams {
    /// Transaction type parameters to build.
    #[serde(flatten)]
    pub tx_type: TransactionTypeBuilder,
    /// Fee to use, if value is fixed,
    /// it will be used as is, otherwise it will be calculated
    #[serde(default)]
    pub fee: FeeBuilder,
    /// Base fee configured, by default, fetch from daemon
    #[serde(default)]
    pub base_fee: BaseFeeMode,
    /// Maximum fee allowed to pay
    /// If the calculated fee is above this value, an error is returned
    pub fee_limit: Option<u64>,
    /// Nonce to use for the transaction
    /// If not present, it will be generated by the wallet
    pub nonce: Option<u64>,
    /// Version to use for the TX
    /// By default, grab the version from wallet
    pub tx_version: Option<TxVersion>,
    /// Cannot be broadcasted if set to false
    #[serde(default = "default_true_value")]
    pub broadcast: bool,
    /// Returns the TX in HEX format also
    #[serde(default = "default_false_value")]
    pub tx_as_hex: bool,
    /// List of private keys to sign the transaction
    /// This allow a person to directly sign in the wallet
    #[serde(default)]
    pub signers: Vec<SignerId>,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct BuildTransactionOfflineParams {
    /// Transaction type parameters to build offline.
    #[serde(flatten)]
    pub tx_type: TransactionTypeBuilder,
    /// Fixed fee is required and must be checked before calling this
    #[serde(default)]
    pub fee: FeeBuilder,
    /// Base fee configured, by default, will use the min base fee
    #[serde(default)]
    pub base_fee: Option<u64>,
    /// Maximum fee allowed to pay
    /// If the calculated fee is above this value, an error is returned
    pub fee_limit: Option<u64>,
    /// Version to use for the TX
    /// By default, grab the version from wallet
    pub tx_version: Option<TxVersion>,
    /// Returns the TX in HEX format also
    #[serde(default = "default_false_value")]
    pub tx_as_hex: bool,
    /// Encrypted balances to use
    /// Assets spent in the transaction must be present
    pub balances: HashMap<Hash, CiphertextCache>,
    /// Reference to use for the transaction
    /// This must point to the most up-to-date topoheight/block hash
    pub reference: Reference,
    /// Nonce to use for the transaction
    pub nonce: u64,
    /// List of private keys to sign the transaction
    /// This allow a person to directly sign in the wallet
    #[serde(default)]
    pub signers: Vec<SignerId>,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct BuildUnsignedTransactionParams {
    /// Transaction type parameters to build without signing.
    #[serde(flatten)]
    pub tx_type: TransactionTypeBuilder,
    /// Fee to use, if value is fixed,
    /// it will be used as is, otherwise it will be calculated
    #[serde(default)]
    pub fee: FeeBuilder,
    /// Base fee configured, by default, fetch from daemon
    #[serde(default)]
    pub base_fee: BaseFeeMode,
    /// Maximum fee allowed to pay
    /// If the calculated fee is above this value, an error is returned
    pub fee_limit: Option<u64>,
    /// Nonce to use for the transaction
    /// If not present, it will be generated by the wallet
    pub nonce: Option<u64>,
    /// Version to use for the TX
    /// By default, grab the version from wallet
    pub tx_version: Option<TxVersion>,
    /// Returns the TX in HEX format also
    #[serde(default = "default_false_value")]
    pub tx_as_hex: bool,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct FinalizeUnsignedTransactionParams {
    /// Unsigned transaction to finalize
    pub unsigned: Hexable<UnsignedTransaction>,
    /// Signatures to append in the transaction
    /// In case it wasn't added in the unsigned already
    #[serde(default)]
    pub signatures: Vec<SignatureId>,
    /// Cannot be broadcasted if set to false
    #[serde(default = "default_true_value")]
    pub broadcast: bool,
    /// Returns the TX in HEX format also
    #[serde(default = "default_false_value")]
    pub tx_as_hex: bool,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct SignUnsignedTransactionParams {
    /// Unsigned transaction hash
    pub hash: Hash,
    /// Signer ID to use for signing the transaction
    pub signer_id: u8
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct UnsignedTransactionResponse {
    /// Unsigned transaction data.
    #[serde(flatten)]
    pub inner: UnsignedTransaction,
    /// Unsigned TX hash for signing for multisig signers
    pub hash: Hash,
    /// Multisig threshold, zero if not active
    pub threshold: Option<u8>,
    /// Unsigned transaction in hex format
    pub tx_as_hex: Option<String>
}

#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug, Copy, Default)]
#[serde(rename_all = "snake_case")]
pub enum BaseFeeMode {
    // let the wallet select the base fee
    #[default]
    None,
    // fixed base fee to use by the wallet
    Fixed(u64),
    // Detected base fee cannot be above it
    Cap(u64),
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct EstimateFeesParams {
    /// Transaction type parameters used for fee estimation.
    #[serde(flatten)]
    pub tx_type: TransactionTypeBuilder,
    /// Fee configuration or amount.
    #[serde(default)]
    pub fee: FeeBuilder,
    /// Base fee configuration.
    #[serde(default)]
    pub base_fee: BaseFeeMode,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct ListTransactionsParams {
    /// Filter by asset
    pub asset: Option<Hash>,
    /// Filter by topoheight range (inclusive)
    pub min_topoheight: Option<TopoHeight>,
    /// Maximum topoheight filter, inclusive.
    pub max_topoheight: Option<TopoHeight>,
    /// Filter by timestamp range (inclusive, milliseconds)
    pub min_timestamp: Option<TimestampMillis>,
    /// Maximum timestamp filter, inclusive.
    pub max_timestamp: Option<TimestampMillis>,
    /// Receiver address for outgoing txs, and owner/sender for incoming
    pub address: Option<Address>,
    /// Contract hash for contract-related transactions.
    pub contract: Option<Hash>,
    /// Whether incoming transactions are included.
    #[serde(default = "default_true_value")]
    pub accept_incoming: bool,
    /// Whether outgoing transactions are included.
    #[serde(default = "default_true_value")]
    pub accept_outgoing: bool,
    /// Whether coinbase transactions are included.
    #[serde(default = "default_true_value")]
    pub accept_coinbase: bool,
    /// Whether burn transactions are included.
    #[serde(default = "default_true_value")]
    pub accept_burn: bool,
    /// Whether blob transactions are included.
    #[serde(default = "default_true_value")]
    pub accept_blob: bool,
    /// Filter by extra data
    pub query: Option<Query>,
    /// Limit the number of entries returned
    pub limit: Option<usize>,
    /// Skip the first N entries
    pub skip: Option<usize>,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct CreateOwnershipProofParams<'a> {
    /// Asset to create the proof for
    pub asset: Cow<'a, Hash>,
    /// If set to None, it is set to current wallet balance topoheight
    /// If set to Some, the balance at requested topoheight will be fetched
    /// and used for the proof creation
    pub topoheight: Option<TopoHeight>,
    /// Amount to prove ownership of.
    pub amount: u64,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct CreateBalanceProofParams<'a> {
    /// Asset to create the proof for
    pub asset: Cow<'a, Hash>,
    /// If set to None, it is set to current wallet balance topoheight
    /// If set to Some, the balance at requested topoheight will be fetched
    /// and used for the proof creation
    pub topoheight: Option<TopoHeight>,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct VerifyHumanReadableProofParams<'a> {
    /// Proof to verify
    pub proof: Cow<'a, HumanReadableProof>,
    /// Address of the prover, used to check the ownership of the proof
    pub address: Cow<'a, Address>,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct TrackAssetParams<'a> {
    /// Asset to track/untrack
    pub asset: Cow<'a, Hash>,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct IsAssetTrackedParams<'a> {
    /// Asset to check
    pub asset: Cow<'a, Hash>,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct GetAssetsParams {
    /// Number of entries to skip.
    pub skip: Option<usize>,
    /// Maximum number of entries to return.
    pub maximum: Option<usize>,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct GetAssetsEntry {
    /// Asset hash.
    pub asset: Hash,
    /// Asset metadata.
    pub data: AssetData,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct TransactionResponse<'a> {
    /// Flattened transaction response.
    #[serde(flatten)]
    pub inner: RPCTransaction<'a>,
    /// Serialized transaction in hexadecimal format when requested.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tx_as_hex: Option<String>
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct GetAssetPrecisionParams<'a> {
    /// Asset hash.
    pub asset: Cow<'a, Hash>
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct GetAddressParams {
    /// Data to use for creating an integrated address
    /// Returned address will contains all the data provided here
    pub integrated_data: Option<DataElement>
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct RescanParams {
    /// Topoheight until which balances and history should be rescanned.
    pub until_topoheight: Option<TopoHeight>,
    /// Whether to reconnect automatically.
    #[serde(default = "default_false_value")]
    pub auto_reconnect: bool
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct SetOnlineModeParams {
    /// Daemon address to connect to.
    pub daemon_address: String,
    /// Whether to reconnect automatically.
    #[serde(default = "default_false_value")]
    pub auto_reconnect: bool,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct NetworkInfoResult {
    /// Information returned by the connected daemon.
    #[serde(flatten)]
    pub inner: daemon::GetInfoResult,
    /// Daemon endpoint currently connected to.
    pub connected_to: String,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct GetBalanceParams {
    /// Optional asset hash, defaulting to XELIS when omitted.
    pub asset: Option<Hash>
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct GetTransactionParams {
    /// Transaction hash to fetch.
    pub hash: Hash
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct SearchTransactionParams<'a> {
    /// Hash used by this field.
    pub hash: Cow<'a, Hash>
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct SearchTransactionResult<'a> {
    /// Matched transaction entry if found.
    pub transaction: Option<TransactionEntry<'a>>,
    /// Storage index where the transaction was found.
    pub index: Option<u64>,
    /// Whether the match came from raw storage search.
    pub is_raw_search: bool
}

#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]
pub struct BalanceChanged {
    /// Asset hash used by this request.
    pub asset: Hash,
    /// New balance amount.
    pub balance: u64
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct VerifySignedDataParams {
    /// Data that was signed
    pub data: DataElement,
    /// Signature to verify
    pub signature: Signature,
    /// Public key of the signer
    pub address: Address,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct GetValueFromKeyParams {
    /// Storage tree name.
    pub tree: String,
    /// Key used by this request.
    pub key: DataValue
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct HasKeyParams {
    /// Storage tree name.
    pub tree: String,
    /// Key used by this request.
    pub key: DataValue
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct GetMatchingKeysParams {
    /// Storage tree name.
    pub tree: String,
    /// Query filter to apply.
    pub query: Option<Query>,
    /// Maximum number of entries to return.
    pub limit: Option<usize>,
    /// Number of entries to skip.
    pub skip: Option<usize>
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct CountMatchingEntriesParams {
    /// Storage tree name.
    pub tree: String,
    /// Key used by this request.
    pub key: Option<Query>,
    /// Value carried by this field.
    pub value: Option<Query>
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct StoreParams {
    /// Storage tree name.
    pub tree: String,
    /// Key used by this request.
    pub key: DataValue,
    /// Value carried by this field.
    pub value: DataElement
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct DeleteParams {
    /// Storage tree name.
    pub tree: String,
    /// Key used by this request.
    pub key: DataValue
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct DeleteTreeEntriesParams {
    /// Storage tree name.
    pub tree: String
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct QueryDBParams {
    /// Storage tree name.
    pub tree: String,
    /// Key used by this request.
    pub key: Option<Query>,
    /// Value carried by this field.
    pub value: Option<Query>,
    /// Maximum number of entries to return.
    pub limit: Option<usize>,
    /// Number of entries to skip.
    pub skip: Option<usize>
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct DecryptExtraDataParams<'a> {
    /// Encrypted data to decrypt
    pub extra_data: Cow<'a, UnknownExtraDataFormat>,
    /// The role we have in the transaction
    /// This is needed to select the correct handle
    pub role: Role,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct DecryptCiphertextParams<'a> {
    /// Ciphertext with the correct handle to use
    pub ciphertext: Cow<'a, CompressedCiphertext>,
    /// Optional maximum supply bound for decryption.
    pub max_supply: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum NotifyEvent {
    // When a new topoheight is detected by wallet
    // it contains the topoheight (u64) as value
    // It may be lower than the previous one, based on how the DAG reacts
    NewTopoHeight,
    // When a new asset is added to wallet
    // Contains a Hash as value
    NewAsset,
    // When a new transaction is added to wallet
    // Contains TransactionEntry struct as value
    NewTransaction,
    // When a balance is changed
    // Contains a BalanceChanged as value
    BalanceChanged,
    // When a rescan happened on the wallet
    // Contains a topoheight as value to indicate until which topoheight transactions got deleted
    Rescan,
    // When the history has been synced again
    // Contains current topoheight as value
    HistorySynced,
    // When network state changed
    Online,
    // Same here
    Offline,
    // Error occuring while syncing
    SyncError,
    // When an asset is tracked in wallet
    TrackAsset,
    // When an asset is untracked from wallet
    UntrackAsset,
    // When a new pending transaction is added to wallet
    // Contains TransactionPending struct as value
    NewPendingTransaction,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct TransferOut<'a> {
    /// Destination address
    pub destination: Cow<'a, Address>,
    /// Asset spent
    pub asset: Cow<'a, Hash>,
    /// Plaintext amount
    pub amount: u64,
    /// extra data
    pub extra_data: Cow<'a, Option<PlaintextExtraData>>
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct TransferIn<'a> {
    /// Asset spent
    pub asset: Cow<'a, Hash>,
    /// Plaintext amount
    pub amount: u64,
    /// extra data
    pub extra_data: Cow<'a, Option<PlaintextExtraData>>
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct DeployInvoke {
    /// Additionnal fees to pay
    /// This is the maximum of gas that can be used by the contract
    /// If a contract uses more gas than this value, the transaction
    /// is still accepted by nodes but the contract execution is stopped
    pub max_gas: u64,
    /// Assets deposited with this call
    pub deposits: IndexMap<Hash, u64>,
}

#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum EntryType<'a> {
    /// Coinbase is only XELIS_ASSET.
    Coinbase {
        /// Coinbase reward amount.
        reward: u64
    },
    Burn {
        /// Asset hash burned.
        asset: Cow<'a, Hash>,
        /// Amount burned.
        amount: u64,
        /// Fee paid.
        fee: u64,
        /// Nonce used.
        nonce: u64
    },
    Incoming {
        /// Source address.
        from: Cow<'a, Address>,
        /// Incoming transfers.
        transfers: Vec<TransferIn<'a>>
    },
    Outgoing {
        /// Outgoing transfers.
        transfers: Vec<TransferOut<'a>>,
        /// Fee paid.
        fee: u64,
        /// Nonce used.
        nonce: u64
    },
    MultiSig {
        /// Multisig participant addresses.
        participants: Cow<'a, Vec<Address>>,
        /// Number of signatures required.
        threshold: u8,
        /// Fee paid.
        fee: u64,
        /// Nonce used.
        nonce: u64
    },
    InvokeContract {
        /// Contract hash.
        contract: Cow<'a, Hash>,
        /// Deposits made.
        deposits: Cow<'a, IndexMap<Hash, u64>>,
        /// Assets received from that call.
        received: Cow<'a, IndexMap<Hash, u64>>,
        /// Invoked chunk identifier.
        chunk_id: u16,
        /// Fee paid.
        fee: u64,
        /// Maximum gas allowed.
        max_gas: u64,
        /// Nonce used.
        nonce: u64
    },
    DeployContract {
        /// Fee paid.
        fee: u64,
        /// Nonce used.
        nonce: u64,
        /// Constructor invocation.
        invoke: Option<Cow<'a, DeployInvoke>>
    },
    IncomingContract {
        /// Transfers received from the contract.
        transfers: Cow<'a, IndexMap<Hash, u64>>,
    },
    OutgoingBlob {
        /// Blob destination addresses.
        destinations: Cow<'a, IndexSet<Address>>,
        /// Fee paid.
        fee: u64,
        /// Nonce used.
        nonce: u64,
        /// Plaintext blob data.
        data: Cow<'a, PlaintextExtraData>,
    },
    IncomingBlob {
        /// Source address.
        from: Cow<'a, Address>,
        /// Blob destination addresses.
        destinations: Cow<'a, IndexSet<Address>>,
        /// Plaintext blob data.
        data: Cow<'a, PlaintextExtraData>,
    }
}

/// This struct is used to represent a transaction entry like in wallet
/// But we replace every PublicKey to use Address instead
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct TransactionEntry<'a> {
    /// Hash used by this field.
    pub hash: Cow<'a, Hash>,
    /// Topoheight used by this request.
    pub topoheight: TopoHeight,
    /// Transaction timestamp in milliseconds.
    pub timestamp: TimestampMillis,
    /// Entry value.
    #[serde(flatten)]
    pub entry: EntryType<'a>,
}

impl std::hash::Hash for TransactionEntry<'_> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.hash.hash(state);
    }
}

impl std::cmp::PartialEq for TransactionEntry<'_> {
    fn eq(&self, other: &Self) -> bool {
        self.hash == other.hash
    }
}

impl std::cmp::Eq for TransactionEntry<'_> {}

/// Pending transaction struct used in wallet to represent a transaction that is not yet confirmed
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct TransactionPending<'a> {
    /// Transaction hash
    pub hash: Cow<'a, Hash>,
    /// At which time the transaction was created
    pub timestamp: TimestampMillis,
    /// Entry data of the transaction
    #[serde(flatten)]
    pub entry: EntryType<'a>,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct EstimateExtraDataSizeParams {
    /// Destination addresses whose integrated data should be measured.
    pub destinations: Vec<Address>,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct EstimateExtraDataSizeResult {
    /// Integrated data size
    pub size: usize,
}
